on: [workflow_dispatch]

name: Windows-installation-check

jobs:
  windows-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Install dependencies
        run: |
          install.packages(c("processx", "remotes", "rcmdcheck", "devtools"), type="binary")
          remotes::install_deps(dependencies = TRUE)
          dotR <- file.path(Sys.getenv("HOME"), ".R")
          if (!file.exists(dotR))
            dir.create(dotR)
          M <- file.path(dotR, "Makevars.win")
          if (!file.exists(M))
            file.create(M)
          cat("\nCXX14FLAGS=-O3 -Wno-unused-variable -Wno-unused-function",
              "CXX14 = $(BINPREF)g++ -m$(WIN) -std=c++1y",
              "CXX11FLAGS=-O3 -Wno-unused-variable -Wno-unused-function",
              file = M, sep = "\n", append = TRUE)
        shell: Rscript {0}

      - name: Install and run r4MAS
        run: |
          remotes::install_github("nmfs-fish-tools/r4MAS")
          library(r4MAS)
          library(Rcpp)
          library(jsonlite)
          r4mas <- Rcpp::Module("rmas", PACKAGE="r4MAS")
          
          # Define area
          area1 <- new(r4mas$Area)
          area1$name <- "area1"
         shell: Rscript {0}
